In [53]:
import numpy as np

$\newcommand{\diag}[1]{\text{diag}\left(#1\right)}$

# An extension to multiple occupations

Suppose that instead of separate sector level labor markets there are $\mathcal{O}$ occupations. Firms in each sector can use any occupation $o$ type labor in production. Our standard framework is the special case where there is exactly one occupation per sector and firms use only their own sector occupation as an input into production. 

## Simulating needed data

For now, I assume production functions are Cobb-Douglass, households have Cobb-Douglas preferences over final consumption goods, and the matching function is Cobb-Douglas. In principle, we don't need to be so restrictive about the functional forms of production and matching. Instead all of the relevant information about production technologies is captured by the levels and changes of the elasticities outline below. Any two production functions with the same elasticities and changes in elasticities would generate the same responses to shocks.

For each sector $i$, we need the elasticity of production of good $j$ with respect to the intermediate input from each other sector $j$, $\varepsilon^{f_i}_{x_{ij}}$, and the elasticity of production with respect to occupation $o$ labor input $N_{io}$, $\varepsilon^{f_i}_{N_{io}}$. I sample elasticites of production on the unit simplex using an exponential transformation of the normal distribution. To start, for each industry, draw
\begin{align*}
    \left(z_{i1}, \cdots,z_{iJ},z_{N_{i1}}, \cdots, z_{N_{i\mathcal{O}}}\right) \sim N\left(\mu,\Sigma\right)
\end{align*}
Then define
\begin{align*}
    \varepsilon^{f_i}_{x_{i1}} = \frac{e^{z_{i1}}}{\sum_{o=1}^{\mathcal{O}}e^{z_{N_{io}}}+\sum_{j=1}^{J}e^{z_{ij}}}
\end{align*}
And equivalently for all other sectors. We also need the elasticities of demand with respect to sector $i$'s output, $\varepsilon^{\mathcal{D}}_{c_i}$. Notice that we can treat the final demand as another production sector that uses no labor input. We can sample the demand elasticities using the same procedure outlined above.

Finally, I sample the matching elasticity with respect to vacancies from a uniform distribution on $[0,1]$. 

We let $\Omega$ be the matrix of input elasticities for each sector and $\Psi = (\bm{I}-\bm{\Omega})^{-1}$ be the Leontif inverse.

In [54]:
# Size of network
J = 4 # number of sectors
O = 2 # number of occupations

# Sampling input-output matrix entries 
μ = np.zeros(J+O)
Σ = np.eye(J+O)
z_draws = np.random.multivariate_normal(μ, Σ, J+1)
elasticity_draws = np.exp(z_draws)/np.sum(np.exp(z_draws),1).reshape((J+1,1))

# Elasticities
epsD = elasticity_draws[0,:-O]/np.sum(elasticity_draws[0,:-O])
epsD = epsD.reshape(J,1)
Omega = elasticity_draws[1:,:-O]
Psi = np.linalg.inv(np.eye(J)-Omega)
epsN = elasticity_draws[1:,J:]

# Drawing elasticity of matching function wrt to U
ν = np.random.uniform(size=O)
epsQ =  -ν.reshape((O,1))
epsF = np.ones((O,1)) + epsQ
epsQ = epsQ.reshape((O,1))
epsF = epsF.reshape((O,1))
curlyQ = np.diag(epsQ.flatten())
curlyF =  np.diag(epsF.flatten())

np.sum(Omega,1) + np.sum(epsN,1) # checking constant returns holds

array([1., 1., 1., 1.])

We need recruiter producer ratios $\tau_o(\theta_o)$ in each occupational labor market. Landais, Michaillat, and Saez (2018) find that the share of recruiters in the US workforce averages around 2.3 percent. I sample recruiter producer ratios uniformly on the interval $[0,0.046]$ to roughly match this fact.

In [55]:
tau = np.random.uniform(low=0,high=0.046,size=(O,1))
curlyT = np.diag(tau.flatten())
curlyT

array([[0.03606975, 0.        ],
       [0.        , 0.02503446]])

Finally, in addition to the data we need assuming one occupation per sector, we need data on employment by sector-occupation pair at the initial equilibrium. For each $i$ and $o$ we need
\begin{align*}
    l_{io} = \frac{\varepsilon^{f_i}_{N_{io}}p_i y_i}{w_o}
\end{align*}
For the purposes of this simple example, we assume that all prices, wages, and quantities are the same and normalized to $1$. This implies that $l_{io} = \varepsilon^{f_i}_{N_{io}}$. 

In [56]:
# labor usage at initial equilibrium
l = epsN
curlyL = l.T/np.sum(l.T,1).reshape((O,1)) 

## Defining shocks
We are interested in the response of sector level and aggregate output and employment to technology shocks $d\log\bm{A}$ and labor force shocks $d\log \bm{H}$. The code below defines the shocks we feed into the model.

In [57]:
# Technology shocks
dlog_A = 0.01*np.ones((J,1))
dlog_H = 0.01*np.zeros((O,1))

## Defining how wages adjust
Since there are mutual gains from trade once an unemployed worker and a firm meet, wages are not pinned down uniquely in models featuring search and matching frictions in the labor market. We must therefore impose a wage schedule, an assumption about how wages change in response to fundamentals, in order to close the model. 

Let $w_o$ be the nominal occupation $o$ wage. 

We need to specify the elasticity of wages to technology shocks and labor force shocks in each sector, $\left\{\left\{\varepsilon^{w_o}_{A_{oi}}\right\}_{i=1}^{J},\left\{\varepsilon^{w_o}_{H_{ok}}\right\}_{k=1}^{\mathcal{O}}\right\}_{o=1}^{\mathcal{O}}$. For instance, a simple assumption is that the response of wages to productivity shocks is proportional to $\varepsilon^{f_i}_{N_{io}}$ and how wages respond to labor force changes is proportional to $\varepsilon^{Q_o}_{\theta_o}$. In general, we express changes in wages as a function of changes in productivity and the labor force. 
\begin{align}
    d\log \bm{w} &= \bm{\Lambda_{A}} d\log \bm{A} + \bm{\Lambda_{H}} d\log \bm{H} \tag{1}
\end{align}
Where $\bm{\Lambda_{A}}$ contains wage elasticities to productivity changes and $\bm{\Lambda_{H}}$ contains wage elasticities to labor force changes.

In [58]:
# Wage elasticities
epsW_A = np.random.uniform(low=0,high=2,size=(O,J))
epsW_H = np.random.uniform(low=-2,high=0,size=(O,O))
epsW_A

array([[0.51933847, 1.9378739 , 0.09631458, 0.7658432 ],
       [0.21221041, 1.27871262, 1.44841686, 1.28584799]])

In [59]:
# Calculating the log change in wages
def WageFunc(dlog_A, dlog_H, epsW_A, epsW_H):
    dlog_w = epsW_A @ dlog_A + epsW_H @ dlog_H
    return dlog_w

In [60]:
#How wages change
dlog_w = WageFunc(dlog_A, dlog_H, epsW_A, epsW_H)
dlog_w = np.zeros_like(dlog_w)
dlog_w

array([[0.],
       [0.]])


## Tightness propagation
We with wage changes in hand, we solve for first order changes in tightness in terms of $d\log\bm{A}$, $d\log\bm{H}$, and $d\log\bm{w}$. The general formula for changes in tightness, treating sector $j$ prices as the numeraire, is
\begin{align}
  d\log \bm{\theta} &=  \left[\diag{\bm{\varepsilon^{\mathcal{F}}_{\theta}}} -\bm{\Xi_{\theta}}\right]^{-1}\left[\left[\left(\bm{\Xi}-\bm{\mu_j}\bm{\Xi_j}\right)\bm{\varepsilon^f_{N}}  - \bm{\mu} \right] d\log \bm{w} + \left[\bm{\Xi}\bm{\varepsilon^f_{N}}-\bm{I}\right]d\log\bm{H} + \bm{\Xi_j}d\log\bm{A} \right] \nonumber\\
    &+  \left[\diag{\bm{\varepsilon^{\mathcal{F}}_{\theta}}} -\bm{\Xi_{\theta}}\right]^{-1}\left[\sum_{i=1}^{J} \bm{\mu_i}d\log {\bm{\varepsilon^{f_i}_{N_i}}}'+\bm{\Xi} \left[ \left(\diag{\bm{\Omega}\bm{1}} - \bm{\Omega}\right)d\log \bm{\lambda} -d\log \bm{\mathcal{E}}\right] \right]  \tag{2}
\end{align}
Where 
\begin{align*}
    \bm{\Xi_\theta}  &=  \left[\bm{\Xi}\bm{\varepsilon^{f}_{N}}\bm{\mathcal{F}} + \bm{\mu_j}\bm{\Xi_j}\bm{\varepsilon^{f}_{N}\bm{\mathcal{Q \Tau}}}\right] \\
    \bm{\Xi} &= \sum_{i=1}^{J} \bm{\mu_i}\bm{\Xi_i} \\ 
    \bm{\mu} &= \sum_{i=1}^{J} \bm{\mu_i} \\
    \bm{\Xi_i} &= \begin{bmatrix} \bm{\Psi_{i}}' & \cdots & \bm{\Psi_i}'\end{bmatrix}_{J \times  \mathcal{O}}'\\
    \bm{\mu_i} &= \diag{\begin{bmatrix} \frac{l_{i1}}{L^d_1} & \cdots & \frac{l_{i\mathcal{O}}}{L^d_{\mathcal{O}}}\end{bmatrix}}
\end{align*}
$\bm{1}$ is a $J\times 1 $ vector of ones and  $d\log \bm{\mathcal{E}}$ is the $J\times 1$ vector of diagonal elements of $\bm{\varepsilon^{f}_{N}} d\log {\bm{\varepsilon^{f}_{N}}}'$.

In [61]:
def curlyEFunc(dlog_epsN,epsN):
    J = epsN.shape[0]
    curlyE = np.diag(epsN @ dlog_epsN.T).reshape(J,1)
    return curlyE

def ThetaFunc2(dlog_A, dlog_H, dlog_w, dlog_epsN, dlog_lam, Psi, Omega, curlyF, curlyQ, curlyT, curlyE, l, epsN, num=0):

    J = dlog_A.shape[0]
    O = dlog_H.shape[0]
    # Creating matrices
    Mu = np.zeros((O,O))
    Xi = np.zeros((O,J))
    for i in range(J):
        Mu = Mu + np.diag(l[i,:] / np.sum(l,0))
        Xi = Xi + (np.diag(l[i,:] / np.sum(l,0))) @ np.tile(Psi[i,:],(O,1))
    
    Mu_j = np.diag(l[num,:] / np.sum(l,0))
    Xi_j = np.tile(Psi[num,:],(O,1))
    Xi_theta = Xi @ epsN @ curlyF + Mu_j @ Xi_j @ epsN @ curlyQ @ curlyT
    I = np.eye(O)
    inv_mat = np.linalg.inv(curlyF - Xi_theta)

    # Contribution of different components
    Cw = inv_mat @ ((Xi - Mu_j @ Xi_j) @ epsN - Mu)
    Ca = inv_mat @ Mu_j @ Xi_j
    Ch = inv_mat @ (Xi @ epsN - I)
    Ce = -inv_mat @ Xi
    Cλ = inv_mat @ Xi @ (np.diag(np.sum(Omega,1)) - Omega)

    # Change in tightness
    dlog_theta = Cw @ dlog_w + Ch @ dlog_H + inv_mat @ np.sum(dlog_epsN.T,1).reshape((O,1)) + Cλ @ dlog_lam + Ce @ curlyE + Ca @ dlog_A

    return dlog_theta

Alternatively, we can write things more compactly using $\bm{\mathcal{L}}$, the $\mathcal{O}\times J$ matrix of sectoral labor shares. We can write
\begin{align*}
     d\log \bm{\theta} &=  \left[\bm{\mathcal{F}} -\bm{\Xi_{\theta}}\right]^{-1}\left[\left[\left[\bm{\mathcal{L}}-\bm{\mathcal{L}_j}\right]\bm{\Psi}\bm{\varepsilon^f_N}-\diag{\bm{\mathcal{L}1}}\right] d\log \bm{w} + \left[\bm{\mathcal{L}}\bm{\Psi}\bm{\varepsilon^f_{N}}-\bm{I}\right]d\log\bm{H} + \bm{\mathcal{L}_j \Psi}d\log\bm{A} \right] \\
    &+  \left[\bm{\mathcal{F}}  -\bm{\Xi_{\theta}}\right]^{-1}\left[\diag{\bm{\mathcal{L}} d\log \bm{\varepsilon^f_{N}}}+\bm{\mathcal{L}}\bm{\Psi} \left[ \left(\diag{\bm{\Omega}\bm{1}} - \bm{\Omega}\right)d\log \bm{\lambda} -d\log \bm{\mathcal{E}}\right] \right] 
\end{align*}
Where $\bm{\Xi_{\theta}} =  \left[\bm{\mathcal{L}}\bm{\Psi}\bm{\varepsilon^f_{N}}\bm{\mathcal{F}}+\bm{\mathcal{L}_j}\bm{\Psi}\bm{\varepsilon^f_N}\bm{\mathcal{Q\Tau}}\right] $ and 
\begin{align*}
    \bm{\mathcal{L}} = \begin{bmatrix}
        \frac{l_{11}}{L^d_1} & \frac{l_{21}}{L^d_{1}} & \cdots & \frac{l_{J1}}{L^d_{1}} \\
        \frac{l_{12}}{L^d_2} & \frac{l_{22}}{L^d_2} & \cdots  & \frac{l_{J2}}{L^d_2} \\
         \vdots & \vdots & \ddots & \vdots \\
        \frac{l_{1\mathcal{O}}}{L^d_{\mathcal{O}}} & \frac{l_{2\mathcal{O}}}{L^d_{\mathcal{O}}} & \cdots & \frac{l_{J\mathcal{O}}}{L^d_{\mathcal{O}}}
    \end{bmatrix},\, \bm{\mathcal{L}_j} = \begin{bmatrix}
        0 & \cdots & \frac{l_{j1}}{L^d_{1}} & \cdots & 0 \\
        0 &\cdots & \frac{l_{j2}}{L^d_2} & \cdots  & 0 \\
         \vdots & \ddots & \vdots & \ddots & \vdots \\
        0 & \cdots & \frac{l_{j\mathcal{O}}}{L^d_{\mathcal{O}}} & \cdots & 0
    \end{bmatrix}
\end{align*}




In [62]:
def ThetaFunc(dlog_A, dlog_H, dlog_w, dlog_epsN, dlog_lam, Psi, Omega, curlyF, curlyQ, curlyT, curlyE, curlyL, epsN, num=0):
    J = dlog_A.shape[0]
    O = dlog_H.shape[0]
    
    # Creating matrices
    curlyL_j = np.zeros_like(curlyL)
    curlyL_j[:,num] = curlyL[:,num]
    Xi = curlyL @ Psi @ epsN @ curlyF + curlyL_j @ Psi @ epsN @ curlyQ @ curlyT 
    inv_mat = np.linalg.inv(curlyF - Xi)
    I = np.eye(O)
    
    # Contribution of different components
    Cw = inv_mat @ ((curlyL-curlyL_j) @ Psi @ epsN - np.diag(np.sum(curlyL,1)))
    Ca = inv_mat @ curlyL_j @ Psi
    Ch = inv_mat @ (curlyL @ Psi @ epsN - I)
    Ce = -inv_mat @ curlyL @ Psi
    Cλ = inv_mat @ curlyL @ Psi @ (np.diag(np.sum(Omega,1)) - Omega)

    # Change in tightness
    dlog_theta = Cw @ dlog_w + Ch @ dlog_H + inv_mat @ np.diag(curlyL @ dlog_epsN).reshape((O,1)) + Cλ @ dlog_lam + Ce @ curlyE + Ca @ dlog_A
    
    return dlog_theta

Assuming Cobb-Douglas production implies $d\log\bm{\varepsilon^f_N} = d\log \bm{\lambda} = 0$.

In [63]:
dlog_epsN = np.zeros((J,O))
curlyE = curlyEFunc(dlog_epsN,epsN)
curlyE

array([[0.],
       [0.],
       [0.],
       [0.]])

Below we compare the two methods to check for consistency, starting with the top method.

In [64]:
dlog_lam = np.zeros_like(dlog_A)
dlog_theta2 = ThetaFunc2(dlog_A, dlog_H, dlog_w, dlog_epsN, dlog_lam, Psi, Omega, curlyF, curlyQ, curlyT, curlyE, l, epsN, num=0)
dlog_theta2 

array([[4.30734349],
       [7.65753787]])

In [65]:
dlog_theta = ThetaFunc(dlog_A, dlog_H, dlog_w, dlog_epsN, dlog_lam, Psi, Omega, curlyF, curlyQ, curlyT, curlyE, curlyL, epsN, num=0)
dlog_theta 

array([[4.30734349],
       [7.65753787]])

In [66]:
dlog_theta-dlog_theta2

array([[ 0.0000000e+00],
       [-8.8817842e-16]])

## Price and output propagation
With changes in tightness in hand, we can now work out how prices and sectoral production changes in response to technology and labor force shocks. Price changes are given by 
\begin{align}
        d\log \bm{p} = \bm{\Psi} \left[\bm{\varepsilon^{f}_{N}} \left[d\log \bm{w} - \bm{\mathcal{Q}} \bm{\mathcal{\Tau} }d\log\bm{\theta}\right] - d\log \bm{A}\right] \tag{3}
\end{align}

In [67]:
def PriceFunc(dlog_A, dlog_w, dlog_theta, Psi, curlyQ, epsN, curlyT):
    # Contributions of different components
    Cw = Psi @ epsN
    Ctheta = -Cw @ curlyQ @ curlyT
    Ca = -Psi

    # Price changes
    dlog_p = Cw @ dlog_w + Ctheta @ dlog_theta + Ca @ dlog_A
    return dlog_p


In [68]:
dlog_p = PriceFunc(dlog_A, dlog_w, dlog_theta, Psi, curlyQ, epsN, curlyT)
dlog_p

array([[ 4.57273108e-15],
       [-5.18762383e-04],
       [-1.00202090e-04],
       [ 3.68657745e-02]])

And output changes are given by
\begin{align}
       d\log \bm{y} &= \bm{\Psi}\left(d\log\bm{A} + \bm{\varepsilon^{f}_{N}}\left(\bm{\mathcal{F}}+\bm{\mathcal{Q}} \bm{\mathcal{\Tau}}\right)d\log \bm{\theta} + \bm{\varepsilon^{f}_{N}} d\log\bm{H}\right)\nonumber \\
    &-\bm{\Psi}d\log \bm{\mathcal{E}} + \bm{\Psi}\left(\diag{\bm{\Omega}\bm{1}} - \bm{\Omega}\right)d\log \bm{\lambda} \tag{4}
\end{align}


In [69]:
def OutputFunc(dlog_A, dlog_H, dlog_theta, dlog_lam, Psi, Omega, curlyQ, curlyF, epsN, curlyT, curlyE):
    # Contributions of different coponents
    Ca = Psi
    Ch = Psi @ epsN
    Ctheta = Ch @ (curlyF + curlyQ @ curlyT)
    Ce = -Psi
    Cλ = Psi @ (np.diag(np.sum(Omega,1)) - Omega)
    
    # Output changes
    dlog_y = Ca @ dlog_A + Ctheta @ dlog_theta + Ch @ dlog_H + Ce @ curlyE + Cλ @ dlog_lam

    return dlog_y

In [70]:
dlog_y = OutputFunc(dlog_A, dlog_H, dlog_theta, dlog_lam, Psi, Omega, curlyQ, curlyF, epsN, curlyT, curlyE)
dlog_y

array([[4.14690841],
       [4.14742717],
       [4.14700861],
       [4.11004263]])

With Cobb-Douglas production, real output should change by the same amount in each sector. This provides an overall check of our code given the Cobb-Douglas assumption.

In [71]:
# Change in nominal GDP
dlog_p + dlog_y

array([[4.14690841],
       [4.14690841],
       [4.14690841],
       [4.14690841]])

We can now check consistency. We should get the same change in labor by either calculating the change in labor supply
\begin{align}
    d\log \bm{L^s} = \text{diag}\left(\mathcal{F}\right) d\log \bm{\theta} + d\log \bm{H} \tag{5}
\end{align}
Or the change in labor demand
\begin{align}
    d\log \bm{L^d} = -J d\log \bm{w} + \sum_{i=1}^{J}\left[d\log \bm{\varepsilon^{f_i}_{N_i}} + d\log \bm{p_i} + d\log\bm{y_i}\right]\tag{6}
\end{align}
Alternatively using $\bm{\mathcal{L}}$, we can write
\begin{align*}
d\log \bm{L^d} = \bm{\mathcal{L}} \left[d\log\bm{p}+d\log\bm{y}\right] + \diag{\bm{\mathcal{L}}d\log \bm{\varepsilon^f_N}} - d\log\bm{w}
\end{align*}

In [72]:
def LaborSupply(dlog_H,dlog_theta,curlyF):
    dlog_Ls = curlyF @ dlog_theta + dlog_H
    return dlog_Ls
    
def LaborDemand2(dlog_w, dlog_y, dlog_p, dlog_epsN, l):
    O = dlog_w.shape[0]
    J = dlog_y.shape[0]
    dlog_Ld = np.zeros((O,1))
    for o in range(O):
        for i in range(J):
            dlog_Ld[o,:] = dlog_Ld[o,:] + l[i,o]/np.sum(l[:,o]) * (dlog_epsN[i,o]  + dlog_y[i,:] + dlog_p[i,:] - dlog_w[o,:])
    return dlog_Ld

def LaborDemand(dlog_w, dlog_y, dlog_p, dlog_epsN, curlyL):
    O = dlog_w.shape[0]
    dlog_Ld = curlyL @ (dlog_p + dlog_y) + np.diag(curlyL @ dlog_epsN).reshape((O,1)) - dlog_w
    return dlog_Ld

Consistency requires
\begin{align*}
    d\log \bm{L^d} - d\log\bm{L^s} = 0
\end{align*}

In [73]:
LaborDemand2(dlog_w, dlog_y, dlog_p, dlog_epsN, l) - LaborSupply(dlog_H,dlog_theta,curlyF)

array([[0.0000000e+00],
       [8.8817842e-16]])

In [74]:
LaborDemand(dlog_w, dlog_y, dlog_p, dlog_epsN, curlyL) - LaborSupply(dlog_H,dlog_theta,curlyF)

array([[0.0000000e+00],
       [8.8817842e-16]])

The aggregate response of output to technology and labor supply shocks is given by 
\begin{align}
   d\log Y = \bm{\varepsilon^{\mathcal{D}}_{c}}' \left[ d\log \bm{\varepsilon^{\mathcal{D}}_{c}}+d\log\bm{y}-d\log\bm{\lambda}\right] \tag{7}
\end{align}

In [79]:
def AggOutputFunc(dlog_y, dlog_lam, dlog_epsD, epsD):
    dlog_aggY = epsD.T @ (dlog_epsD + dlog_y - dlog_lam)
    return dlog_aggY

Assuming Cobb-Douglas, $d\log\bm{\varepsilon^{\mathcal{D}}_{c}}=0$. 

In [81]:
dlog_epsD = np.zeros_like(dlog_y)
dlog_aggY = AggOutputFunc(dlog_y, dlog_lam, dlog_epsD, epsD)
dlog_aggY

array([[4.13797772]])

## Special case with one occupation per sector
Basic setup.

In [75]:
# Size of network
J = 4 # number of sectors
O = J # number of occupations

# Sampling input-output matrix entries 
μ = np.zeros(J+O)
Σ = np.eye(J+O)
z_draws = np.random.multivariate_normal(μ, Σ, J+1)
elasticity_draws = np.exp(z_draws)/np.sum(np.exp(z_draws),1).reshape((J+1,1))

# Elasticities
epsD = elasticity_draws[0,:-O]/np.sum(elasticity_draws[0,:-O])
epsD = epsD.reshape(J,1)
Omega = elasticity_draws[1:,:-O]
Psi = np.linalg.inv(np.eye(J)-Omega)
epsN = np.diag(np.sum(elasticity_draws[1:,J:],1))
l = epsN

# Drawing elasticity of matching function wrt to U
ν = np.random.uniform(size=O)
epsQ =  -ν.reshape((O,1))
epsF = np.ones((O,1)) + epsQ
epsQ = epsQ.reshape((O,1))
epsF = epsF.reshape((O,1))
curlyQ = np.diag(epsQ.flatten())
curlyF =  np.diag(epsF.flatten())

np.sum(Omega,1) + np.sum(epsN,1) # checking constant returns holds

array([1., 1., 1., 1.])

In [76]:
tau = np.random.uniform(low=0,high=0.046,size=(O,1))
curlyT = np.diag(tau.flatten())
curlyT

array([[0.02319921, 0.        , 0.        , 0.        ],
       [0.        , 0.00769664, 0.        , 0.        ],
       [0.        , 0.        , 0.0038407 , 0.        ],
       [0.        , 0.        , 0.        , 0.0154689 ]])

Wage changes.

In [77]:
# Wage elasticities
epsW_A = np.random.uniform(low=0,high=2,size=(O,J))
epsW_H = np.random.uniform(low=-2,high=0,size=(O,O))

# Technology shocks
dlog_A = 0.01*np.ones((J,1))
dlog_H = 0.01*np.zeros((O,1))

dlog_w = WageFunc(dlog_A, dlog_H, epsW_A, epsW_H)
dlog_w = np.zeros_like(dlog_w)
dlog_w

array([[0.],
       [0.],
       [0.],
       [0.]])

Changes in tightness.

In [78]:

dlog_epsN = np.zeros((J,O))
curlyE = curlyEFunc(dlog_epsN,epsN)
dlog_lam = np.zeros_like(dlog_A)

dlog_theta = ThetaFunc(dlog_A, dlog_H, dlog_w, dlog_epsN, dlog_lam, Psi, Omega, curlyF, curlyQ, curlyT, curlyE, curlyL, epsN, num=0)
dlog_theta

TypeError: ThetaFunc() missing 1 required positional argument: 'epsN'

Changes in prices.

In [ ]:
dlog_p = PriceFunc(dlog_A, dlog_w, dlog_theta, Psi, curlyQ, epsN, curlyT)
dlog_p

array([[-1.70002901e-16],
       [-1.60978718e-02],
       [-2.21109558e-02],
       [-8.86068649e-03]])

Changes in Output.

In [ ]:
dlog_y = OutputFunc(dlog_A, dlog_H, dlog_theta, dlog_lam, Psi, curlyQ, curlyF, epsN, curlyT, curlyE)
dlog_y

array([[0.04055621],
       [0.05665408],
       [0.06266716],
       [0.04941689]])

Checking results.

In [ ]:
dlog_p + dlog_y

array([[0.04055621],
       [0.04055621],
       [0.04055621],
       [0.04055621]])

In [ ]:
LaborDemand(dlog_w, dlog_y, dlog_p, dlog_epsN, l) - LaborSupply(dlog_H,dlog_theta,curlyF)

array([[-1.80411242e-16],
       [ 0.00000000e+00],
       [ 1.38777878e-17],
       [ 0.00000000e+00]])