In [3]:
import numpy as np

# A simple numerical example on simulated data

## Simulating needed data

For now, I assume production functions are Cobb-Douglass, households have Cobb-Douglas preferences over final consumption goods, and the matching function is Cobb-Douglas. In principle, we don't need to be so restrictive about the functional forms of production and matching. Instead all of the relevant information about production technologies is captured by the levels and changes of the elasticities outline below. Any two production functions with the same elasticities and changes in elasticities would generate the same responses to shocks.

For each sector $j$, we need the elasticity of production of good $j$ with respect to the intermediate input from each other sector $i$, $\varepsilon^{f_j}_{x_{ji}}$, and the elasticity of production with respect to the labor input $N_j$, $\varepsilon^{f_j}_{N_{j}}$. I sample elasticites of production on the unit simplex using an exponential transformation of the normal distribution. To start, for each industry, draw
\begin{align*}
    \left(z_{j1}, \cdots,z_{jJ},z_{N_j}\right) \sim N\left(\mu,\Sigma\right)
\end{align*}
Then define
\begin{align*}
    \varepsilon^{f_j}_{x_{j1}} = \frac{e^{z_{j1}}}{e^{z_{N_j}}+\sum_{k=1}^{J}e^{z_{jk}}}
\end{align*}
And equivalently for all other sectors. We also need the elasticities of demand with respect to sector $j$'s output, $\varepsilon^{\mathcal{D}}_{c_j}$. Notice that we can treat the final demand as another production sector that uses no labor input. We can sample the demand elasticities using the same procedure outlined above.

Finally, I sample the matching elasticity with respect to vacancies from a uniform distribution on $[0,1]$. 

We let $\bm{\Omega}$ be the matrix of input elasticities for each sector and $\bm{I}-\bm{\Psi}$ be the Leontif inverse.

In [17]:
# Size of network
J = 4 

# Sampling input-output matrix entries 
μ = np.zeros(J+1)
Σ = np.eye(J+1)
z_draws = np.random.multivariate_normal(μ, Σ, J+1)
elasticity_draws = np.exp(z_draws)/np.sum(np.exp(z_draws),1).reshape((J+1,1))

# Elasticities
epsD = elasticity_draws[0,:-1]/np.sum(elasticity_draws[0,:-1])
Omega = elasticity_draws[1:,:-1]
Psi = np.linalg.inv(np.eye(J)-Omega)
epsN = np.diag(elasticity_draws[1:,-1])

# Drawing elasticity of matching function wrt to U
ν = np.random.uniform(size=J)
curlyQ = np.diag(-ν)
curlyF =  np.eye(J) - curlyQ

Finally, we need recruiter producer ratios $\tau_j(\theta_j)$ in each sector. Landais, Michaillat, and Saez (2018) find that the share of recruiters in the US workforce averages around 2.3 percent. I sample recruiter producer ratios uniformly on the interval $[0,0.046]$ to roughly match this fact.

In [18]:
tau = np.diag(np.random.uniform(low=0,high=0.046,size=J))

## Defining shocks
We are interested in the response of sector level and aggregate output and employment to technology shocks $d\log\bm{A}$ and labor force shocks $d\log \bm{H}$. The code below defines the shocks we feed into the model.

In [19]:
# Technology shocks
dlog_A = 0.01*np.ones(J)
dlog_H = 0.01*np.ones(J)

## Defining how wages adjust
Since there are mutual gains from trade once an unemployed worker and a firm meet, wages are not pinned down uniquely in models featuring search and matching frictions in the labor market. We must therefore impose a wage schedule, an assumption about how wages change in response to fundamentals, in order to close the model. 

In particular, we need to specify the elasticity of wages to technology shocks and labor force shocks in each sector, $\left\{\left\{\varepsilon^{w_j}_{A_{ji}},\varepsilon^{w_j}_{H_{ji}}\right\}_{i=1}^{J}\right\}_{j=1}^{J}$. For instance, a simple, but unrealistic, assumption is that wages respond positively to own sector productivity and negatively to own sector labor force, but do not respond to changes in other sectors. In general, we express changes in wages as a function of changes in productivity and the labor force. 
\begin{align}
    d\log \bm{w} &= \bm{\Lambda_{A}} d\log \bm{A} + \bm{\Lambda_{H}} d\log \bm{H} \tag{1}
\end{align}
Where $\bm{\Lambda_{A}}$ contains wage elasticities to productivity changes and $\bm{\Lambda_{H}}$ contains wage elasticities to labor force changes.

In [20]:
# Wage elasticities
epsW_A = np.diag(np.random.uniform(low=0,high=2,size=J))
epsW_H = np.diag(np.random.uniform(low=-2,high=0,size=J))

In [21]:
# Calculating the log change in wages
def WageFunc(dlog_A, dlog_H, epsW_A, epsW_H):
    dlog_w = epsW_A @ dlog_A + epsW_H @ dlog_H
    return dlog_w

In [22]:
#How wages change
dlog_w = WageFunc(dlog_A, dlog_H, epsW_A, epsW_H)
dlog_w

array([-0.00872009, -0.00021771, -0.00127489, -0.00011357])

## Tightness propagation
We with wage changes in hand, we solve for first order changes in tightness in terms of $d\log\bm{A}$, $d\log\bm{H}$, and $d\log\bm{w}$. The general formula for changes in tightness, treating sector 1 prices as the numeraire, is
\begin{align}
    d \log \bm{\theta} &=\left(\text{diag}\left(\bm{\mathcal{F}}\right)-\bm{\Xi_{\theta}}\right)^{-1}\left(\left(\bm{I} - \bm{\Psi} \text{diag}\left(\bm{\varepsilon^f_N}\right)\right) \left(d\log \bm{\varepsilon^f_N} + d\log \bm{\lambda} - d\log \bm{H}\right) + \bm{\Xi_{A}} d\log \bm{A}\right) \nonumber \\
    &- \left(\text{diag}\left(\bm{\mathcal{F}}\right)-\bm{\Xi_{\theta}}\right)^{-1} \left(\bm{I}-\bm{\Xi}_{w}\right)d\log \bm{w} \tag{2}
\end{align}
Where 
\begin{align*}
    \bm{\Xi_{A}} &= \begin{bmatrix}
        \Psi_1 \\
        \bm{0} \\
        \vdots \\
        \bm{0}
    \end{bmatrix}, \, \bm{\Xi_\theta} = \begin{bmatrix}
        \Psi_1 \varepsilon^{f_1}_{N_1}\left(\varepsilon^{\mathcal{F}_1}_{\theta_1} + \tau_1(\theta_1)\varepsilon^{\mathcal{Q}_1}_{\theta_1}\right) \\
        \Psi_2 \varepsilon^{f_2}_{N_2} \varepsilon^{\mathcal{F}_2}_{\theta_2} \\
        \vdots \\
        \Psi_J \varepsilon^{f_J}_{N_J} \varepsilon^{\mathcal{F}_J}_{\theta_J}
    \end{bmatrix}, \bm{\Xi_{w}} = \begin{bmatrix}
        \bm{0} \\
        \Psi_2 \varepsilon^{f_2}_{N_2} \\
        \vdots\\
        \Psi_J \varepsilon^{f_J}_{N_J}
    \end{bmatrix}
\end{align*}

In [23]:
def ThetaFunc(dlog_A, dlog_H, dlog_w, dlog_epsN, dlog_lam, Psi, curlyF, curlyQ, epsN, tau, num = 0):
    
    # Creating matrices
    Xi_a = np.zeros_like(Psi)
    Xi_a[num,:] = Psi[num,:]

    Xi_theta = Psi @ epsN @ curlyF
    Xi_theta[num,:] = Xi_theta[num,:] + Psi[num,:] * epsN[num,num] * tau[num,num] * curlyQ[num,num]

    Xi_w = Psi @ epsN 
    Xi_w[num,:] = num

    I = np.eye(Psi.shape[0])

    # Contribution of different components
    Cw = np.linalg.inv(curlyF - Xi_theta) @ (I - Xi_w)
    Ca = np.linalg.inv(curlyF - Xi_theta) @ Xi_a 
    Ch = np.linalg.inv(curlyF - Xi_theta) @ (I - Psi @ epsN)

    # Change in tightness
    dlog_theta = Ch @ (dlog_epsN + dlog_lam - dlog_H) + Ca @ dlog_A - Cw @ dlog_w

    return dlog_theta

Assuming Cobb-Douglas production implies $d\log\bm{\varepsilon^f_N} = d\log \bm{\lambda} = 0$.

In [24]:
dlog_epsN = np.zeros_like(dlog_A)
dlog_lam = np.zeros_like(dlog_A)
dlog_theta = ThetaFunc(dlog_A, dlog_H, dlog_w, dlog_epsN, dlog_lam, Psi, curlyF, curlyQ, epsN, tau)
dlog_theta

array([2.37858758, 2.10371906, 2.35906925, 2.99975784])

## Price and output propagation
With changes in tightness in hand, we can now work out how prices and sectoral production changes in response to technology and labor force shocks. Price changes are given by 
\begin{align}
    d \log \bm{p} &=\bm{\Psi} \left(
        \text{diag}\left(\bm{\varepsilon^{f}_{N}}\right) d\log\bm{w} -\text{diag}\left(\bm{\varepsilon^{f}_{N}}\right)\text{diag}\left(\bm{\tau}\right)\text{diag}\left(\bm{\varepsilon^{\mathcal{Q}}_{\theta}}\right)d\log\bm{\theta} - d\log \bm{A} \right) \tag{3}
\end{align}
Since we have assumed that sector one is the numerair, we need to check that price changes are consistent with this assumption. Unfortunately, below it looks like they are not, which means we may have to think a bit harder about the pricing equation. 

In [25]:
def PriceFunc(dlog_A, dlog_w, Psi, curlyQ, epsN, tau):
    # Contributions of different components
    Cw = Psi @ epsN 
    Ct = Psi @ epsN @ tau @ curlyQ
    Ca = Psi
    # Price changes
    dlog_p = Cw @ dlog_w - Ct @ dlog_theta - Ca @dlog_A
    return dlog_p

In [26]:
dlog_p = PriceFunc(dlog_A, dlog_w, Psi, curlyQ, epsN, tau)
dlog_p

array([-0.03354115, -0.042352  , -0.02758359, -0.03912562])

And output changes are given by
\begin{align}
    d\log \bm{y} &= \bm{\Psi}\left(d\log\bm{A} + \text{diag}\left(\bm{\varepsilon^{f}_{N}}\right)\left(\text{diag}\left(\bm{\mathcal{F}}\right)+\text{diag}\left(\bm{\tau}\right)\text{diag}\left(\bm{\varepsilon^{\mathcal{Q}}_{\theta}}\right)\right)d\log \bm{\theta} + \text{diag}\left(\bm{\varepsilon^{f}_{N}}\right) d\log\bm{H}\right) \nonumber\\
    &-\bm{\Psi} \text{diag}\left(\bm{\varepsilon^{f}_{N}}\right) d\log \bm{\varepsilon^{f}_{N}} + \left(\bm{I} - \bm{\Psi}\text{diag}\left(\bm{\varepsilon^{f}_{N}}\right)\right) d\log \bm{\lambda} \tag{4}
\end{align}


In [15]:
def OutputFunc(dlog_A, dlog_H, dlog_theta, dlog_epsN, dlog_lam, Psi, curlyQ, curlyF, epsN, tau):
    # Contributions of different coponents
    Ca = Psi
    Ct = Psi @ epsN @ (curlyF + tau @ curlyQ) 
    Ch = Psi @ epsN 
    I = np.eye(Psi.shape[0])

    # Changes in output
    dlog_y = Ca @ dlog_A + Ct @ dlog_theta + Ch @ (dlog_H-dlog_epsN) + (I - Ch) @ dlog_lam 

    return dlog_y

In [16]:
dlog_y = OutputFunc(dlog_A, dlog_H, dlog_theta, dlog_epsN, dlog_lam, Psi, curlyQ, curlyF, epsN, tau)
dlog_y

array([19.24733442, 19.26450972, 19.24913698, 19.25027176])

## Unemployment
We can use changes in tightness and the labor force to calculate changes in employment. 
\begin{align}
    d\log \bm{L} = \text{diag}\left(\mathcal{F}\right) d\log \bm{\theta} + d\log \bm{H} \tag{5}
\end{align}

In [27]:
def EmploymentFunc(dlog_H,dlog_theta,curlyF):
    dlog_L = curlyF @ dlog_theta + dlog_H
    return dlog_L

In [28]:
dlog_L = EmploymentFunc(dlog_H,dlog_theta,curlyF)
dlog_L

array([4.01773125, 4.00922887, 4.01028604, 4.00912473])

Unemployment in sector $j$ is $U_j = H_j - L_j$. The unemployment rate in sector $j$ is $u_j = \frac{H_j-L_j}{H_j}$.


## Aggregation