In [2]:
import numpy as np
import pandas as pd

$\newcommand{\diag}[1]{\text{diag}\left(#1\right)}$
# US Exercise

We are going to use the data calibrated to the US economy to evaluate the impact of technology and labor supply shocks. 

In [78]:
data_dir = '../data/clean/'
dfA      = pd.read_csv(data_dir + 'A.csv')
dfParam  = pd.read_csv(data_dir + 'params.csv')
dfLshare = pd.read_csv(data_dir + 'labor_share.csv')
dfLabor_market_yearly= pd.read_csv(data_dir + 'labor_market_yearly.csv')
dfLabor_market_yearly = dfLabor_market_yearly.sort_values(by=['year', 'BEA_sector'])
dfLabor_market_yearly = dfLabor_market_yearly.dropna(axis=0)
dfLabor_market_yearly = dfLabor_market_yearly[dfLabor_market_yearly['year'] == 2005]
# reformatting parameters
Omega = np.array(dfA.iloc[:, 1:], dtype='float64')
Psi = np.linalg.inv(np.eye(Omega.shape[0])-Omega)
J = Omega.shape[0]

φ = np.array(dfParam.φ)

epsN = np.diag(np.array(dfParam.α))
epsD = np.array(dfParam.θ_alt)

We need to convert the paramters from the data to the right format for our code. We need the input matrix $\Omega$, diagonal matrices of matching elasticities and the production elasticity to labor. In addition our data contains separate matching efficiencies for each sector. We need to encorporate these into the matrices $\diag{\bm{\mathcal{Q}}}$, $\diag{\bm{\mathcal{F}}}$, and $\diag{\bm{\tau}}$.

In [53]:
θ = dfLabor_market_yearly['v'] / dfLabor_market_yearly['u'] 
ν = np.ones(J) * 0.5
curlyQ = np.diag(-ν)
curlyF =  np.eye(J) + curlyQ
r = 0.045
tau = np.diag(r / (φ*θ**(-ν) - r))
# NOTE: here I am picking the r so the τ's roughly loook right. Down the line, we can calibrate τ directly from the data. 
# Also note that tightness is computed from unemployed workers, but in our model it should be computed from the whole work force.
tau

array([[0.02299856, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.01846423, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.01315401, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.03653684, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.      

## Defining shocks
We are interested in the response of sector level and aggregate output and employment to technology shocks $d\log\bm{A}$ and labor force shocks $d\log \bm{H}$. The code below defines the shocks we feed into the model.

In [80]:
# Technology shocks
dlog_A = 0.01*np.zeros(J)
dlog_A[0] = 0.01
dlog_H = 0.01*np.zeros(J)

## Defining how wages adjust
Since there are mutual gains from trade once an unemployed worker and a firm meet, wages are not pinned down uniquely in models featuring search and matching frictions in the labor market. We must therefore impose a wage schedule, an assumption about how wages change in response to fundamentals, in order to close the model. 

Let $W_i$ be the nominal sector wage and $w_i = W_i / P_i$ the wage for sector i adjusted for goods price in that sector. 

In particular, we need to specify the elasticity of wages to technology shocks and labor force shocks in each sector, $\left\{\left\{\varepsilon^{w_j}_{A_{ji}},\varepsilon^{w_j}_{H_{ji}}\right\}_{i=1}^{J}\right\}_{j=1}^{J}$. For instance, a simple, but unrealistic, assumption is that wages respond positively to own sector productivity and negatively to own sector labor force, but do not respond to changes in other sectors. In general, we express changes in wages as a function of changes in productivity and the labor force. 
\begin{align}
    d\log \bm{w} &= \bm{\Lambda_{A}} d\log \bm{A} + \bm{\Lambda_{H}} d\log \bm{H} \tag{1}
\end{align}
Where $\bm{\Lambda_{A}}$ contains wage elasticities to productivity changes and $\bm{\Lambda_{H}}$ contains wage elasticities to labor force changes.

In [81]:
# Wage elasticities
# Start with fixed real wages
epsW_A = np.zeros_like(Psi)
epsW_H = np.zeros_like(Psi)
epsW_A

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0

In [82]:
# Calculating the log change in wages
def WageFunc(dlog_A, dlog_H, epsW_A, epsW_H):
    dlog_wR = epsW_A @ dlog_A + epsW_H @ dlog_H
    return dlog_wR

In [83]:
#How wages change
dlog_wR = WageFunc(dlog_A, dlog_H, epsW_A, epsW_H)
dlog_wR

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])


## Tightness propagation
We with wage changes in hand, we solve for first order changes in tightness in terms of $d\log\bm{A}$, $d\log\bm{H}$, and $d\log\bm{w}$. The general formula for changes in tightness, treating sector 1 prices as the numeraire, is
\begin{align}
    d \log \bm{\theta} &=\left(\diag{\bm{\mathcal{F}}}-\bm{\Xi_{\theta}}\right)^{-1}\left(\left(\bm{I} - \bm{\Psi} \diag{\bm{\varepsilon^f_N}}\right) \left(d\log \bm{\varepsilon^f_N} + d\log \bm{\lambda} - d\log \bm{H}\right) + \bm{\Psi} d\log \bm{A}\right) \\
    &- \left(\diag{\bm{\mathcal{F}}}-\bm{\Xi_{\theta}}\right)^{-1} \left(d\log \bm{w}-d\log\bm{p}\right) \tag{2}
\end{align}
Where 
\begin{align*}
    \bm{\Xi_\theta} = \bm{\Psi}\diag{\bm{\varepsilon^f_N}}\left(\diag{\bm{\mathcal{F}}} + \diag{\bm{\tau}}\diag{\bm{\varepsilon^{\mathcal{Q}}_{\theta}}}\right)
\end{align*}

In [84]:
def ThetaFunc(dlog_A, dlog_H, dlog_wR, dlog_epsN, dlog_lam, Psi, curlyF, curlyQ, epsN, tau):
    
    # Creating matrices
    Xi_a = Psi

    Xi_theta = Psi @ epsN @ curlyF+ Psi @ epsN @ tau @ curlyQ
    #Xi_theta[num,:] = Xi_theta[num,:] + Psi[num,:] @ epsN @ tau @ curlyQ

    Xi_w = np.zeros_like(Psi)

    I = np.eye(Psi.shape[0])

    # Contribution of different components
    Cw = np.linalg.inv(curlyF - Xi_theta) @ (I - Xi_w)
    Ca = np.linalg.inv(curlyF - Xi_theta) @ Xi_a 
    Ch = np.linalg.inv(curlyF - Xi_theta) @ (I - Psi @ epsN)

    # Change in tightness
    dlog_theta = Ch @ (dlog_epsN + dlog_lam - dlog_H) + Ca @ dlog_A - Cw @ dlog_wR

    return dlog_theta

Assuming Cobb-Douglas production implies $d\log\bm{\varepsilon^f_N} = d\log \bm{\lambda} = 0$.

In [85]:
dlog_epsN = np.zeros_like(dlog_A)
dlog_lam = np.zeros_like(dlog_A)
dlog_theta = ThetaFunc(dlog_A, dlog_H, dlog_wR, dlog_epsN, dlog_lam, Psi, curlyF, curlyQ, epsN, tau)
dlog_theta

array([0.06445944, 0.02849834, 0.02718066, 0.0270991 , 0.02739871,
       0.02726356, 0.02636078, 0.02751739, 0.02750465, 0.02745732,
       0.02751818, 0.02734066, 0.02828448, 0.02892574, 0.02773318,
       0.02794294, 0.02725074])

## Price and output propagation
With changes in tightness in hand, we can now work out how prices and sectoral production changes in response to technology and labor force shocks. Price changes are given by 
\begin{align}
    \left(I - \Psi\text{diag}\left(\bm{\varepsilon^{f}_{N}}\right)\right)d \log \bm{p} &=\bm{\Psi} \left(
        \text{diag}\left(\bm{\varepsilon^{f}_{N}}\right) \left(d\log\bm{w}  - d\log\bm{p}\right) -\text{diag}\left(\bm{\varepsilon^{f}_{N}}\right)\text{diag}\left(\bm{\tau}\right)\text{diag}\left(\bm{\varepsilon^{\mathcal{Q}}_{\theta}}\right)d\log\bm{\theta} - d\log \bm{A} \right) \tag{3}
\end{align}
While $\Xi = \left(I - \Psi\text{diag}\left(\bm{\varepsilon^{f}_{N}}\right)\right)$ is not invertible, we impose an additional restrction $d\log p_i = 0$, with the good produced by sector $i$ the numeraire good of our choice.

In [86]:
def PriceFunc(dlog_A, dlog_wR, dlog_theta, Psi, curlyQ, epsN, tau, num=0):
    # Contributions of different components
    Cw = Psi @ epsN 
    Cw[num, :] = 0
    Ct = Psi @ epsN @ tau @ curlyQ
    Ct[num, :] = 0
    Ca = np.copy(Psi)
    Ca[num, :] = 0
    
    Xi = np.eye(Psi.shape[0]) - Psi @ epsN 
    Xi[num, :] = 0
    Xi[num, num] = 1

    # Price changes
    dlog_p = np.linalg.inv(Xi) @ (Cw @ dlog_wR - Ct @ dlog_theta - Ca @dlog_A)
    return dlog_p


In [87]:
num = 0
dlog_p = PriceFunc(dlog_A, dlog_wR, dlog_theta, Psi, curlyQ, epsN, tau, num)
dlog_p

array([0.        , 0.01798055, 0.01863939, 0.01868017, 0.01853037,
       0.01859794, 0.01904933, 0.01847102, 0.01847739, 0.01850106,
       0.01847063, 0.01855939, 0.01808748, 0.01776685, 0.01836313,
       0.01825825, 0.01860435])

Alternatively, we can solve explicitly for $d\log\bm{p}$ 
\begin{align*}
    d\log \bm{p} &= \bm{\Xi_p}^{-1}\text{diag}\left(\bm{\varepsilon^{f}_{N}}\right) \left(d\log\bm{w} - d\log \bm{p}\right)\nonumber \\
    &-\bm{\Xi_p}^{-1}\text{diag}\left(\bm{\varepsilon^{f}_{N}}\right)\text{diag}\left(\bm{\tau}\right)\text{diag}\left(\bm{\varepsilon^{\mathcal{Q}}_{\theta}}\right)d\log\bm{\theta}\\
    &- \bm{\Xi_p}^{-1} d\log \bm{A}
\end{align*}
Where
\begin{align*}
    \bm{\Xi_{p}} &= \begin{bmatrix}
        0 & \bm{0}_{1\times (J-1)} \\
        \bm{0}_{(J-1)\times 1} & \bm{I}_{(J-1) \times (J-1)} - \diag{\bm{\varepsilon^f_N}\setminus\varepsilon^{f_1}_{N_1}}
    \end{bmatrix} - \bm{\Omega}
\end{align*}
The two solution methods should coincide to machine precision. 

In [88]:
def PriceFunc2(dlog_A, dlog_wR, dlog_theta, Omega, curlyQ, epsN, tau, num = 0):
    Xi_p = np.eye(Omega.shape[0]) - epsN 
    Xi_p[num, : ] = 0 
    Xi_p = Xi_p - Omega
    dlog_p = np.linalg.inv(Xi_p) @ (epsN @ (dlog_wR - tau @ curlyQ @ dlog_theta) - dlog_A)
    return dlog_p

In [89]:
dlog_p2 = PriceFunc2(dlog_A, dlog_wR, dlog_theta, Omega, curlyQ, epsN, tau, num)
dlog_p2


array([1.79977561e-15, 1.79805493e-02, 1.86393877e-02, 1.86801677e-02,
       1.85303656e-02, 1.85979381e-02, 1.90493274e-02, 1.84710218e-02,
       1.84773909e-02, 1.85010594e-02, 1.84706306e-02, 1.85593861e-02,
       1.80874801e-02, 1.77668486e-02, 1.83631283e-02, 1.82582464e-02,
       1.86043482e-02])

We can check that our solution is consistent with $p_i$ being the numeraire by checking that 
\begin{align*}
    0 & = \varepsilon^{f_i}_{N_i} \left( d\log w_i - d\log p_i - \tau_i(\theta_i) \varepsilon^{\mathcal{Q_i}}_{\theta_i} d\log \theta_i\right)+\Omega_i d\log\bm{p} - d\log A_i 
\end{align*}

In [90]:
epsN[num,num] * (dlog_wR[num] - tau[num,num] * curlyQ[num,num] * dlog_theta[num]) + Omega[num,] @ dlog_p - dlog_A[num]

-2.1354445989274495e-15

In [91]:
epsN[num,num] * (dlog_wR[num] - tau[num,num] * curlyQ[num,num] * dlog_theta[num]) + Omega[num,] @ dlog_p2 - dlog_A[num]

-1.734723475976807e-18

Finally, we can check that our two solution methods coincide, providing another sanity check on our code.

In [92]:
dlog_p - dlog_p2

array([-1.79977561e-15, -4.00027234e-15, -3.99680289e-15, -3.98986399e-15,
       -4.00374178e-15, -3.99680289e-15, -3.97945565e-15, -3.98639455e-15,
       -3.96904731e-15, -3.99333344e-15, -3.97945565e-15, -3.99333344e-15,
       -3.98639455e-15, -4.00027234e-15, -3.98639455e-15, -3.99333344e-15,
       -3.98986399e-15])

And output changes are given by
\begin{align}
    d\log \bm{y} &= \bm{\Psi}\left(d\log\bm{A} + \text{diag}\left(\bm{\varepsilon^{f}_{N}}\right)\left(\text{diag}\left(\bm{\mathcal{F}}\right)+\text{diag}\left(\bm{\tau}\right)\text{diag}\left(\bm{\varepsilon^{\mathcal{Q}}_{\theta}}\right)\right)d\log \bm{\theta} + \text{diag}\left(\bm{\varepsilon^{f}_{N}}\right) d\log\bm{H}\right) \nonumber\\
    &-\bm{\Psi} \text{diag}\left(\bm{\varepsilon^{f}_{N}}\right) d\log \bm{\varepsilon^{f}_{N}} + \left(\bm{I} - \bm{\Psi}\text{diag}\left(\bm{\varepsilon^{f}_{N}}\right)\right) d\log \bm{\lambda} \tag{4}
\end{align}


In [93]:
def OutputFunc(dlog_A, dlog_H, dlog_theta, dlog_epsN, dlog_lam, Psi, curlyQ, curlyF, epsN, tau):
    # Contributions of different coponents
    Ca = Psi
    Ct = Psi @ epsN @ (curlyF + tau @ curlyQ) 
    Ch = Psi @ epsN 
    I = np.eye(Psi.shape[0])

    # Changes in output
    dlog_y = Ca @ dlog_A + Ct @ dlog_theta + Ch @ (dlog_H-dlog_epsN) + (I - Ch) @ dlog_lam 

    return dlog_y

In [94]:
dlog_y = OutputFunc(dlog_A, dlog_H, dlog_theta, dlog_epsN, dlog_lam, Psi, curlyQ, curlyF, epsN, tau)
dlog_y

array([0.03222972, 0.01424917, 0.01359033, 0.01354955, 0.01369935,
       0.01363178, 0.01318039, 0.0137587 , 0.01375233, 0.01372866,
       0.01375909, 0.01367033, 0.01414224, 0.01446287, 0.01386659,
       0.01397147, 0.01362537])

With Cobb-Douglas production, real output should change by the same amount in each sector. This provides an overall check of our code given the Cobb-Douglas assumption.

In [95]:
# Change in nominal GDP
dlog_p + dlog_y

array([0.03222972, 0.03222972, 0.03222972, 0.03222972, 0.03222972,
       0.03222972, 0.03222972, 0.03222972, 0.03222972, 0.03222972,
       0.03222972, 0.03222972, 0.03222972, 0.03222972, 0.03222972,
       0.03222972, 0.03222972])

We can now check consistency. We should get the same change in labor by either calculating the change in labor supply
\begin{align}
    d\log \bm{L^s} = \text{diag}\left(\mathcal{F}\right) d\log \bm{\theta} + d\log \bm{H} \tag{5}
\end{align}
Or the change in labor demand
\begin{align}
    d\log \bm{L^d} = d\log \bm{\varepsilon^{f}_N} + d\log \bm{p} + d\log\bm{y} - d\log\bm{w} \tag{6}
\end{align}

In [96]:
def LaborSupply(dlog_H,dlog_theta,curlyF):
    dlog_Ls = curlyF @ dlog_theta + dlog_H
    return dlog_Ls
    
def LaborDemand(dlog_wR, dlog_y, dlog_epsN):
    dlog_Ld = dlog_epsN  + dlog_y - dlog_wR
    return dlog_Ld

Consistency requires
\begin{align*}
    d\log \bm{L^d} - d\log\bm{L^s} = 0
\end{align*}

In [97]:
LaborDemand(dlog_wR, dlog_y, dlog_epsN) - LaborSupply(dlog_H,dlog_theta,curlyF)

array([ 6.93889390e-18,  1.73472348e-18, -1.73472348e-18,  1.73472348e-18,
        1.73472348e-18,  3.46944695e-18, -1.73472348e-18, -1.73472348e-18,
       -3.46944695e-18,  0.00000000e+00, -6.93889390e-18, -3.46944695e-18,
        1.73472348e-18, -5.20417043e-18,  0.00000000e+00, -1.73472348e-18,
       -3.46944695e-18])

## Unemployment
We can use changes in tightness and the labor force to calculate changes in employment. 
\begin{align}
    d\log \bm{L} = \text{diag}\left(\mathcal{F}\right) d\log \bm{\theta} + d\log \bm{H} \tag{5}
\end{align}

In [98]:
dlog_L = LaborSupply(dlog_H,dlog_theta,curlyF)
dlog_L

array([0.03222972, 0.01424917, 0.01359033, 0.01354955, 0.01369935,
       0.01363178, 0.01318039, 0.0137587 , 0.01375233, 0.01372866,
       0.01375909, 0.01367033, 0.01414224, 0.01446287, 0.01386659,
       0.01397147, 0.01362537])

Unemployment in sector $j$ is $U_j = H_j - L_j$. The log change in Unemployment is 
\begin{align}
    d\log \bm{U} = \diag{\bm{U}}^{-1}\left(\diag{\bm{H}} d\log \bm{H} - \diag{L}d\log\bm{L}\right)\tag{6}
\end{align}
The unemployment rate in sector $j$ is $u_j = \frac{H_j-L_j}{H_j}$. The log change in the unemployment rate is 
\begin{align}
    d\log \bm{u} = \left(\bm{I} - \diag{\bm{u}}\right)\diag{\bm{u}}^{-1} \left(d\log\bm{H} - d\log\bm{L}\right) \tag{7}
\end{align}


In [99]:
def UnemploymentFunc(dlog_H, dlog_L, U, H, L):
    dlog_U = np.linalg.inv(U) @ (H @ dlog_H - L @ dlog_L)
    return dlog_U

def UnRateFunc(dlog_H, dlog_L, u):
    dlog_u = (np.eye(dlog_H.shape[0]) - u) @ np.linalg.inv(u) @ (dlog_H - dlog_L)
    return dlog_u

## Aggregation
Given first order changes in output, we can use the elasticities of demand and changes in domar weights calculate changes in aggregate output.
\begin{align}
    d\log Y = \bm{\varepsilon^{\mathcal{D}}_{c}}' \left(d\log\bm{\varepsilon^{\mathcal{D}}_{c}} + d\log \bm{y} - d\log \bm{\lambda}\right) \tag{8}
\end{align}

In [100]:
def AggOutputFunc(dlog_y, dlog_epsD, dlog_lam, epsD):
    dlog_Y = epsD.T @ (dlog_epsD + dlog_y - dlog_lam)
    return dlog_Y

Assuming Cobb-Douglas, $d\log \bm{\varepsilon^{\mathcal{D}}_{c}} = d\log \bm{\lambda} = \bm{0}$. 

In [101]:
dlog_epsD = np.zeros_like(dlog_A)
dlog_Y = AggOutputFunc(dlog_y, dlog_epsD, dlog_lam, epsD)
dlog_Y

0.014732540586415127